# Generated by Django 4.1.13 on 2024-01-15 05:56

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=20)),
                ('dateOfBirth', models.CharField(max_length=20)),
                ('userId', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'app_users',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('options', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
                ('quizId', models.CharField(max_length=150)),
                ('correctOption', models.IntegerField()),
                ('imageUrl', models.CharField(max_length=150, null=True)),
            ],
            options={
                'db_table': 'quizzes',
            },
        ),
        migrations.CreateModel(
            name='QuizNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('options', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
                ('quizId', models.CharField(max_length=150)),
                ('correctOption', models.IntegerField()),
                ('subject', models.CharField(default='Public Administration', max_length=100)),
                ('imageUrl', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizName', models.CharField(max_length=100)),
                ('userId', models.CharField(max_length=100)),
                ('userName', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('correctAnswers', models.IntegerField()),
                ('totalQuestions', models.IntegerField()),
                ('time', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_results',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('imageUrl', models.CharField(max_length=250)),
                ('quizList', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'db_table': 'subject_names',
            },
        ),
    ]
